### ISSUE TITLE
Why are you "execute requests" and "send responses" for server commands? You can execute your server commands without this step(All commands are in the server)

### ISSUE THREAD

**Issue by DmitriBazilov** [k1b24/LaboratoryWork6#5]
https://github.com/k1b24/LaboratoryWork6/blob/992ae75c21973d5ade7e0679f344698533eef850/LaboratoryWork6/lab-server/src/main/java/kib/lab6/server/ConsoleListenerThread.java#L38-L53

**Comment by k1b24** [comment]
I don't send responses back, I just show the response to the user on server. It's just has the same logic as on client, and there is no sense to change the logic here(sdai 6uyu snachala, potom pogovorim)
